#!/usr/bin/env python3
"""Bootstrap empty rebuild5 schemas for a fresh Citus cluster.

This intentionally creates distributed/reference metadata before any data load.
It is used by upgrade v2 so the large raw GPS table can be loaded with COPY
after Citus already knows its distribution key.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

os.environ.setdefault("PGOPTIONS", "-c auto_explain.log_analyze=off")

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from rebuild5.backend.app.core.database import execute
from rebuild5.backend.app.enrichment.schema import ensure_enrichment_schema
from rebuild5.backend.app.etl.source_prep import bootstrap_metadata_tables
from rebuild5.backend.app.maintenance.schema import ensure_maintenance_schema
from rebuild5.backend.app.profile.pipeline import ensure_profile_schema


def ensure_base_schemas() -> None:
    for schema in ("rb5", "rb5_meta", "rb5_stage", "rb5_bench"):
        execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")


def ensure_raw_gps_full_backup() -> None:
    execute(
        """
        CREATE TABLE IF NOT EXISTS rb5.raw_gps_full_backup (
            "记录数唯一标识" character varying(100),
            "数据来源dna或daa" character varying(45),
            did character varying(200),
            ts character varying(45),
            ip character varying(45),
            pkg_name character varying(45),
            wifi_name character varying(100),
            wifi_mac character varying(45),
            sdk_ver character varying(45),
            "gps上报时间" character varying(45),
            "主卡运营商id" character varying(45),
            "品牌" character varying(45),
            "机型" character varying(45),
            gps_info_type character varying(45),
            "原始上报gps" character varying(200),
            cell_infos text,
            ss1 text,
            "当前数据最终经度" double precision,
            "当前数据最终纬度" double precision,
            android_ver character varying(45),
            cpu_info character varying(200),
            "基带版本信息" character varying(200),
            arp_list text,
            "压力" character varying(45),
            imei character varying(45),
            oaid character varying(200)
        )
        """
    )
    execute("CREATE INDEX IF NOT EXISTS idx_raw_gps_full_backup_ts ON rb5.raw_gps_full_backup (ts)")
    execute(
        """
        CREATE INDEX IF NOT EXISTS idx_raw_gps_full_backup_uid
        ON rb5.raw_gps_full_backup ("记录数唯一标识")
        """
    )


def ensure_bench_notes() -> None:
    execute(
        """
        CREATE TABLE IF NOT EXISTS rb5_bench.notes (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id text,
            topic text,
            severity text,
            body text,
            created_at timestamp with time zone DEFAULT now()
        )
        """
    )
    execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_dist_partition
                WHERE logicalrelid = 'rb5_bench.notes'::regclass
            ) THEN
                PERFORM create_reference_table('rb5_bench.notes');
            END IF;
        END $$;
        """
    )


def bootstrap_schema() -> None:
    ensure_base_schemas()
    bootstrap_metadata_tables()
    ensure_raw_gps_full_backup()
    ensure_bench_notes()
    ensure_profile_schema()
    ensure_enrichment_schema()
    ensure_maintenance_schema()


def main() -> None:
    bootstrap_schema()


if __name__ == "__main__":
    main()
